### ISSUE TITLE
How to make this work with wordpress?

### ISSUE THREAD

**Issue by FawadNL** [attitude/rfpl-cache-php#1]
I have created a plugin out of this and wrote a function like this (function works and is fired) but its not caching RFPL:

```
require_once 'vendor/autoload.php';

add_action('init', 'load_rfpl_cache');
function load_rfpl_cache(){
	$cache = new \RFPL\Cache();
	try { $cache->serve(); } catch (\Exception $e) {}
}
```

**Comment by attitude** [comment]
I needed to wire this before the WordPress even starts doing its thing, e.g. in the index.php. I doubt this is straightforward to implement as a regular plugin. It's possible but I wouldn't go this road because there are way too many things that can go wrong, e.g. with other plugins.

**Comment by attitude** [comment]
I'm closing this issue. Feel free to re-open if you feel like want to add anything.
